name: Workspace Linux

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_dev_DEBUG: 0

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test
